1) Identify the checked exceptions in below 

A) ArithmeticException B) ParseException c) NumberFormatException D) ArrayIndexOutOfBoundsException

2) Identify which statements are true 
a) finally block code excutes mandetorily
b) try without catch is possible
c) one try block contains multiple catch blocks
d) all the above

3) What is the output for below code
public class P17 {
    public static void main(String[] args) {
        try {
            System.out.println("B");
            throw new NumberFormatException();
        } catch(ArithmeticException e) {
            System.out.println("A");
        } catch(Exception e) {
            System.out.println("C");
        } finally {
            System.out.println("Z");
        }
    }
}

A) B Z B) B C Z C) A C Z D) B A Z

4) What would be output for below code

public class P17 {
    public static void main(String[] args) {
        try {
            System.out.println("B");
            throw new NumberFormatException();
        } catch(ArithmeticException e) {
            System.out.println("A");
        } catch(NumberFormatException e) {
	   System.out.println("X");
	} catch(Exception e) {
            System.out.println("C");
        } finally {
            System.out.println("Z");
        }
    }
}

A) B X Z B) B A Z C) B C Z D) Compile Time Error 

5) What would be output for below code

public class E1 {

	static {
	      try {throw new ArithmeticException("my exception");

	      }
	      catch(ArithmeticException e) {
		System.out.println("3");
	      }
	      catch(Exception e){
	        System.out.println("2");
	      }
	    }
	 
	    public static void main(String[] args){
	      System.out.println("1");
	    }
}

A) 1 2 B) 3 1 C) Compile Time Error D) Runtime Error

6) What would be output for below code

public class E1 {
	static {
	      try {throw new ArithmeticException("my exception");

	      }
	       catch(ArithmeticException e) {
	         System.out.println("3");
	       }
	      catch(Exception e){
	        System.out.println("2");
	      }
	    }
	 
	    public static void main(String[] args){
	      System.out.println("1");
	    }
}

A) 1 1 B) 2 2 C) 3 1 D) Runtime Error 

7) What would be output for below code

public class P31 {
    public static void main(String[] args) {
        try {
            int a=5;
            int b=4;
            int c=a/b;
            System.out.println("Hi");
        } catch(ArithmeticException e) {
            System.out.println("Divex");
        } finally {
            System.out.println("Program End...");
        }
    }
}

A) Compile Time Error B) Hi Program End C) DivEx Program End D) Program End 

8) What would be output for below code

public class P23 {
    public static void main(String[] args) {
        int[] a=new int[5];
        try {
            a[6]=5/0;
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Array Size Small...");
        } catch(ArithmeticException e) {
            System.out.println("Division By Zero Impossible");
        } catch(Exception e) {
            System.out.println("General Exception");
        }
    }
}

A) Division by zero impossible B) Array Size Small C) General Exception D) None

9) What would be output for below code

public class P23 {
    public static void main(String[] args) {
        int[] a=new int[5];
        try {
            a[6]=5/3;
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Array Size Small...");
        } catch(ArithmeticException e) {
            System.out.println("Division By Zero Impossible");
        } catch(Exception e) {
            System.out.println("General Exception");
        }
    }
}

A) Division by zero Impossible B) General Exception C) None D) Array Size is Small

10) What is the output ofr below code 

public class E1 {
	public static void main(String[] args) {
		  try {
	            int a=5;
	            int b=4;
	            int c=a/b;
	            System.out.println("Hi");
	        }
		  catch (Exception e) {
			  System.out.println("Error");
		  }
		  catch(ArithmeticException e) {
	            System.out.println("Divex");
	        } finally {
	            System.out.println("Program End...");
	        }
	}
}
